apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-cluster-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      # Apps that live in their own repos
      - app: sample-app
        cluster: dev
        repoURL: https://github.com/andywatts/sample-app
        path: chart
        valuesFile: environments/values-dev.yaml
      # Platform infrastructure (Kong) in k8s-apps repo
      - app: kong
        cluster: dev
        repoURL: https://github.com/andywatts/k8s-apps
        path: charts/kong
        valuesFile: values/dev/kong.yaml
  template:
    metadata:
      name: '{{cluster}}-{{app}}'
    spec:
      project: dev
      source:
        repoURL: '{{repoURL}}'
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
