apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-cluster-apps
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - app: sample-app
          - app: kong
      - list:
          elements:
          - cluster: staging
  template:
    metadata:
      name: '{{cluster}}-{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andywatts/k8s-apps
        targetRevision: main
        path: 'charts/{{app}}'
        helm:
          valueFiles:
          - '../../values/{{cluster}}/{{app}}.yaml'
      destination:
        # Update this server URL when staging cluster is created
        server: https://kubernetes.default.svc
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
