apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-cluster-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/andywatts/k8s-apps
      revision: main
      files:
      - path: values/staging/*.yaml
  template:
    metadata:
      name: 'staging-{{path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andywatts/k8s-apps
        targetRevision: main
        path: 'charts/{{path.basenameNormalized}}'
        helm:
          valueFiles:
          - '../../{{path}}'
      destination:
        # Update this server URL when staging cluster is created
        server: https://kubernetes.default.svc
        namespace: '{{path.basenameNormalized}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
