apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-cluster-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/andywatts/k8s-apps
      revision: main
      directories:
      - path: clusters/staging/*
  template:
    metadata:
      name: 'staging-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andywatts/k8s-apps
        targetRevision: main
        path: '{{path}}'
      destination:
        # Update this server URL when staging cluster is created
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

