apiVersion: v2
name: kong
description: Kong API Gateway in DB-less mode with Ingress Controller
type: application
version: 1.0.0
appVersion: "3.5"

dependencies:
  - name: kong
    version: 2.38.0
    repository: https://charts.konghq.com

